[theme]
base = "dark"
# El color primario cian brillante del mockup
primaryColor = "#00E5FF"
# Fondo azul muy oscuro casi negro
backgroundColor = "#0b0f19"
# Fondo secundario para los paneles y tarjetas
secondaryBackgroundColor = "#161b26"
textColor = "#ffffff"
font = "sans serif"

[client]
showErrorDetails = false

[ui]
hideTopBar = true